<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 08.03.17
 * Time: 13:36
 */

namespace rollun\callback;

use Psr\Http\Message\ServerRequestInterface as Request;
use rollun\actionrender\Interfaces\LazyLoadMiddlewareGetterInterface;
use rollun\actionrender\LazyLoadMiddlewareGetter\Attribute;
use rollun\actionrender\MiddlewareDeterminator\AttributeParam;
use rollun\callback\Middleware\Factory\InterruptorMiddlewareFactory;
use rollun\datastore\Middleware\Factory\DataStoreMiddlewareFactory;
use Zend\ServiceManager\Factory\FactoryInterface;

/**
 * Class InterruptMiddlewareDeterminator
 * @package rollun\callback
 */
class InterruptMiddlewareDeterminator extends AttributeParam
{
    const INTERRUPT_MIDDLEWARE_PREFIX = "InterruptMiddleware";

    /**
     * @param Request $request
     * @return string
     */
    public function getMiddlewareServiceName(Request $request)
    {
        $serviceName = parent::getMiddlewareServiceName($request); // TODO: Change the autogenerated stub
        return $serviceName . static::INTERRUPT_MIDDLEWARE_PREFIX;
    }


}
