<?php
/**
 * @copyright Copyright © 2014 Rollun LC (http://rollun.com/)
 * @license LICENSE.md New BSD License
 */

namespace rollun\test\Interruptor\Callback;

use rollun\callback\Callback\SerializedCallback;
use rollun\callback\Callback\Interrupter\Process;
use rollun\test\Callback\CallbackTestDataProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-13 at 12:52:54.
 */
class ProcessTest extends CallbackTestDataProvider
{
    public function testParallelProcess()
    {
        $callback = new SerializedCallback(function ($file) {
            sleep(2);
            $time = microtime(1);
            file_put_contents($file, "$time\n", FILE_APPEND);
        });

        $outPutFile = "data/testOutput.dat";

        (new Process($callback))($outPutFile);
        (new Process($callback))($outPutFile);
        sleep(3);
        $timeData = file_get_contents($outPutFile);
        list($firstTime, $secondTime) = explode("\n", $timeData);
        if (abs($firstTime - $secondTime) < 0.5) {
            $result = 'parallel';
        } else {
            $result = 'in series';
        }
        if (substr(php_uname(), 0, 7) === "Windows") {
            $this->assertEquals('in series', $result);
        } else {
            $this->assertEquals('parallel', $result);
        }

        unlink($outPutFile);
    }
}
