<?php

/**
 * @copyright Copyright © 2014 Rollun LC (http://rollun.com/)
 * @license LICENSE.md New BSD License
 */

namespace Rollun\Test\Unit\Callback\Interruptor;

use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;
use Rollun\Test\Support\TimestampWriterCallback;
use rollun\callback\Callback\CallbackException;
use rollun\callback\Callback\SerializedCallback;
use rollun\callback\Callback\Interrupter\Process;
use rollun\logger\Writer\Stream;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-13 at 12:52:54.
 */
class ProcessTest extends TestCase
{
    protected const TEST_OUTPUT_TILE = 'data/testOutput.log';

    protected function tearDown(): void
    {
        unlink(self::TEST_OUTPUT_TILE);
    }

    public function testParallelProcess()
    {
        // What is under test is that the two child processes overlap in time. The callback is
        // a named invokable rather than a closure so that it reaches the child natively:
        // a closure would go through opis/closure, an anonymous class would not serialize.
        $callback = new SerializedCallback(new TimestampWriterCallback(1));

        (new Process($callback))(self::TEST_OUTPUT_TILE);
        (new Process($callback))(self::TEST_OUTPUT_TILE);
        sleep(3);
        $timeData = file_get_contents(self::TEST_OUTPUT_TILE);
        [$firstTime, $secondTime] = explode("\n", $timeData);
        if (abs((float) $firstTime - (float) $secondTime) < 0.5) {
            $result = 'parallel';
        } else {
            $result = 'in series';
        }
        if (str_starts_with(php_uname(), "Windows")) {
            $this->assertEquals('in series', $result);
        } else {
            $this->assertEquals('parallel', $result);
        }
    }

    public function testUnserializedCallbackProcess()
    {
        global $container;

        $callback = new SerializedCallback(new class {
            public function __invoke() {}
        });

        $logger = $container->get(LoggerInterface::class);
        foreach ($logger->getWriters() as $writer) {
            $writer->shutdown();
        }
        $logger->addWriter(new Stream(self::TEST_OUTPUT_TILE));

        $process = new Process($callback, null, null, $logger);

        $this->expectException(CallbackException::class);

        $process();
    }

    public function testUnserializedCallbackProcessLogging()
    {
        global $container;

        $callback = new SerializedCallback(new class {
            public function __invoke() {}
        });

        $logger = $container->get(LoggerInterface::class);
        foreach ($logger->getWriters() as $writer) {
            $writer->shutdown();
        }
        $logger->addWriter(new Stream(self::TEST_OUTPUT_TILE));

        $process = new Process($callback, null, null, $logger);

        try {
            $process();
        } catch (\Throwable) {

        }

        $log = file_get_contents(self::TEST_OUTPUT_TILE);
        $this->assertNotEmpty($log);
    }
}
