name: Check PHP 8.1

on:
  push:
    branches: [ master, 8.x ]
  pull_request:
    branches: [ master, 8.x ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # https://github.com/docker/compose/issues/7306
      COMPOSE_INTERACTIVE_NO_CLI: 1
    steps:
      - uses: actions/checkout@v2

      - name: Check project
        run: make init check down